Prefix: "&8[ &a&lSERVER &8]&r "
UpdateLoresTimer: 18
UpdateServersTimer: 20
Serverlist:
  hub:
    Ip: localhost
    Port: 25565
  prison:
    Ip: localhost
    Port: 25566
  kitpvp:
    Ip: localhost
    Port: 25567
  skyblock:
    Ip: localhost
    Port: 25568
lang:
  online:
    true: "online"
    false: "offline"
  onlineplayers:
    0: "None."
    10: "&a&l10&r"